package com.liuyihtu.mclash.root

import org.junit.Assert.*
import org.junit.Test
import org.yaml.snakeyaml.Yaml

class RootRuntimeConfigTest {
    @Test fun runtimeOverridesConflictingListenersButRetainsRoutingAndUpstreamDns() {
        val source = """
            mixed-port: 9999
            tproxy-port: 8888
            tun: {enable: true, auto-route: true}
            listeners: [{name: public, type: mixed, port: 7777, listen: 0.0.0.0}]
            external-controller-tls: 0.0.0.0:4443
            external-controller-unix: /tmp/core.sock
            external-ui-url: https://example.com/ui.zip
            routing-mark: 123
            secret: imported-secret
            dns:
              enable: false
              listen: 0.0.0.0:53
              ipv6: true
              enhanced-mode: fake-ip
              nameserver: [https://dns.example/dns-query]
              default-nameserver: [8.8.8.8]
              nameserver-policy: {example.com: 1.1.1.1}
            proxies: [{name: a, type: socks5, server: example.com, port: 1080}]
            rules: [MATCH,a]
        """.trimIndent()
        val runtime = Yaml().load<Map<String, Any>>(RootRuntimeConfig.build(source, false))
        assertFalse(runtime.containsKey("tun"))
        assertFalse(runtime.containsKey("listeners"))
        assertFalse(runtime.containsKey("external-controller-tls"))
        assertFalse(runtime.containsKey("external-controller-unix"))
        assertFalse(runtime.containsKey("external-ui-url"))
        assertEquals(RootRuntimeConfig.TPROXY_PORT, runtime["tproxy-port"])
        assertEquals("127.0.0.1", runtime["bind-address"])
        assertEquals("", runtime["secret"])
        assertEquals("dashboard", runtime["external-ui"])
        assertEquals("127.0.0.1:9090", runtime["external-controller"])
        assertEquals(listOf("MATCH", "a"), runtime["rules"])
        val dns = runtime["dns"] as Map<*, *>
        assertEquals(listOf("https://dns.example/dns-query"), dns["nameserver"])
        assertEquals(mapOf("example.com" to "1.1.1.1"), dns["nameserver-policy"])
        assertEquals("0.0.0.0:${RootRuntimeConfig.DNS_PORT}", dns["listen"])
        assertEquals(false, dns["ipv6"])
        assertEquals("redir-host", dns["enhanced-mode"])
        assertEquals(listOf("8.8.8.8"), dns["default-nameserver"])
    }

    @Test fun missingDnsGetsUsableLocalResolver() {
        val text = RootRuntimeConfig.build("rules: ['MATCH,DIRECT']", true)
        assertTrue(text.contains("# Generated by Mclash Root; IPv4 TProxy, local device only.\nmixed-port:"))
        assertFalse(text.startsWith("\n"))
        val runtime = Yaml().load<Map<String, Any>>(text)
        val dns = runtime["dns"] as Map<*, *>
        assertEquals(true, dns["enable"])
        assertEquals(listOf("114.114.114.114"), dns["nameserver"])
        assertEquals("debug", runtime["log-level"])
    }

    @Test fun runtimePreservesMclashMetadataWithBomAndWindowsLineEndings() {
        val metadata = """
            # Mclash 全局链路: {"front":["wap"]}
            # Mclash 节点链路: {"CN北京LTˇ⁴A-x1":"wap","🇰🇷 韩国80":"wap"}
            # Mclash HTTP/WS Host: "gw.alicdn.com"
            # Mclash 国内正则: "北京|广州"
            # Mclash 国外正则: "日本B|韩国"
            # Mclash 代理组正则: {"🚀 国内":"北京|广州","🌍 国外":"日本B|韩国","测速":"^JP"}
            # Mclash 手动节点: ["wap","🇰🇷 韩国80","🇨🇳 广州443"]
            # Mclash 链路代理组: {"Chain":["wap"]}
        """.trimIndent()
        val source = metadata + "\n" + """
            proxies: [{name: wap, type: http, server: example.com, port: 80}]
            rules: ['MATCH,wap']
            description: |
              # Mclash 国内正则: "literal text, not metadata"
        """.trimIndent()
        val text = RootRuntimeConfig.build("\uFEFF" + source.replace("\n", "\r\n"), false)
        val expected = listOf(6, 2, 1, 7, 5).joinToString("\n") { metadata.lines()[it].replace("# Mclash 节点链路: ", "# Mclash 前置链路 1: ") }
        assertTrue(text.startsWith("$expected\n"))
        val banner = "# Generated by Mclash Root; IPv4 TProxy, local device only."
        assertTrue(text.contains("$banner\nmixed-port:"))
        assertTrue(text.indexOf("rules:") < text.indexOf(banner))
        assertTrue(text.indexOf("dns:") < text.indexOf(banner))
        val runtime = Yaml().load<Map<String, Any>>(text)
        assertEquals(listOf("MATCH,wap"), runtime["rules"])
        assertEquals("wap", ((runtime["proxies"] as List<*>).single() as Map<*, *>)["name"])
        assertEquals("# Mclash 国内正则: \"literal text, not metadata\"", runtime["description"])
        // Rebuilding a runtime copy must not duplicate the metadata.
        val rebuilt = RootRuntimeConfig.build(text, true)
        assertEquals(expected.lines(), rebuilt.lines().filter { it.startsWith("# Mclash ") })
        assertEquals(1, rebuilt.lines().count { it == banner })
    }

    @Test(expected = Exception::class) fun ambiguousDuplicateSettingsAreRejected() {
        RootRuntimeConfig.build("dns: {}\ndns: {enable: false}", false)
    }
}
